version: '3.3'
services:
  db:
    image: mysql:5.7
    secrets:
      - mypass
      - mydatabase
    environment:
      MYSQL_DATABASE_FILE: '/run/secret/mydatabase'
      # Password for root access
      MYSQL_ROOT_PASSWORD_FILE: '/run/secret/mypass'
secrets:
   mypass:
     file: ./mysql_password
   mydatabase:
     file: ./mysql_database
